# Generated by Django 5.0.7 on 2024-07-12 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('modul', 'Modul'), ('exercise', 'Exercise')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mapel.activity')),
                ('description', models.TextField()),
            ],
            bases=('mapel.activity',),
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mapel.activity')),
                ('file', models.FileField(upload_to='modules')),
            ],
            bases=('mapel.activity',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.mapel')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='mapel.topic'),
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('used', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.exercise')),
            ],
        ),
    ]
