# Generated by Django 5.0.7 on 2024-07-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0003_alter_activity_id_alter_soal_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='modules'),
        ),
    ]
