# Generated by Django 5.0.7 on 2024-07-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0004_alter_modul_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='content_suggestion',
            field=models.TextField(blank=True),
        ),
    ]
